-- Task #661 — PV packages, immutable confirmed revisions and reserve ledger.
CREATE TABLE IF NOT EXISTS marche_lot_assignments (id serial PRIMARY KEY, marche_id integer NOT NULL REFERENCES marches(id) ON DELETE CASCADE, lot_id integer NOT NULL REFERENCES lots(id) ON DELETE CASCADE, assigned_by text NOT NULL, assigned_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, removed_by text, removed_at timestamp, source text NOT NULL DEFAULT 'manual', note text, CONSTRAINT marche_lot_assignments_source_chk CHECK (source IN ('manual','devis_suggestion')), CONSTRAINT marche_lot_assignments_removed_audit_chk CHECK ((removed_at IS NULL) = (removed_by IS NULL)));--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS marche_lot_assignments_active_unique ON marche_lot_assignments(marche_id,lot_id) WHERE removed_at IS NULL;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS pv_packages (id serial PRIMARY KEY, project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE, marche_id integer NOT NULL REFERENCES marches(id), contractor_id integer NOT NULL REFERENCES contractors(id), reference text NOT NULL, reception_kind text NOT NULL, reception_date date NOT NULL, status text NOT NULL DEFAULT 'draft', source text NOT NULL DEFAULT 'native', supersedes_package_id integer, version integer NOT NULL DEFAULT 1, created_by text NOT NULL, created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by text, updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, confirmed_by text, confirmed_at timestamp, superseded_by text, superseded_at timestamp, CONSTRAINT pv_packages_reception_kind_chk CHECK (reception_kind IN ('partial','final')), CONSTRAINT pv_packages_status_chk CHECK (status IN ('draft','confirmed','sent_for_signature','signed','delivered','superseded','legacy')), CONSTRAINT pv_packages_source_chk CHECK (source IN ('native','legacy_import')), CONSTRAINT pv_packages_version_positive_chk CHECK (version > 0), CONSTRAINT pv_packages_confirmed_audit_chk CHECK (status NOT IN ('confirmed','sent_for_signature','signed','delivered','superseded') OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)), CONSTRAINT pv_packages_superseded_audit_chk CHECK (status != 'superseded' OR (superseded_by IS NOT NULL AND superseded_at IS NOT NULL)));--> statement-breakpoint
DO $$ BEGIN ALTER TABLE pv_packages ADD CONSTRAINT pv_packages_supersedes_package_id_fk FOREIGN KEY (supersedes_package_id) REFERENCES pv_packages(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS pv_packages_project_id_idx ON pv_packages(project_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS pv_packages_marche_id_idx ON pv_packages(marche_id);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS pv_package_lots (package_id integer NOT NULL REFERENCES pv_packages(id) ON DELETE CASCADE, lot_id integer NOT NULL REFERENCES lots(id), assignment_id integer NOT NULL REFERENCES marche_lot_assignments(id), added_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pv_package_lots_package_lot_unique UNIQUE(package_id,lot_id));--> statement-breakpoint
CREATE TABLE IF NOT EXISTS pv_package_documents (id serial PRIMARY KEY, package_id integer NOT NULL REFERENCES pv_packages(id) ON DELETE CASCADE, document_kind text NOT NULL, display_order integer NOT NULL DEFAULT 0, title text NOT NULL, original_filename text NOT NULL, original_storage_key text NOT NULL, original_mime_type text NOT NULL, original_sha256 text NOT NULL, original_size_bytes integer NOT NULL, pdf_storage_key text NOT NULL, pdf_sha256 text NOT NULL, pdf_page_count integer NOT NULL, uploaded_by text NOT NULL, uploaded_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pv_package_documents_kind_chk CHECK (document_kind IN ('base','annex')), CONSTRAINT pv_package_documents_display_order_chk CHECK(display_order >= 0), CONSTRAINT pv_package_documents_original_sha256_chk CHECK(original_sha256 ~ '^[0-9a-f]{64}$'), CONSTRAINT pv_package_documents_pdf_sha256_chk CHECK(pdf_sha256 ~ '^[0-9a-f]{64}$'), CONSTRAINT pv_package_documents_size_chk CHECK(original_size_bytes > 0 AND pdf_page_count > 0));--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS pv_package_documents_one_base_unique ON pv_package_documents(package_id) WHERE document_kind='base';--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS pv_package_documents_annex_order_unique ON pv_package_documents(package_id,display_order) WHERE document_kind='annex';--> statement-breakpoint
CREATE TABLE IF NOT EXISTS pv_reserves (id serial PRIMARY KEY, project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE, marche_id integer REFERENCES marches(id), contractor_id integer REFERENCES contractors(id), title text NOT NULL, description text, severity text NOT NULL, status text NOT NULL DEFAULT 'open', owner text, due_date date, version integer NOT NULL DEFAULT 1, created_by text NOT NULL, created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by text, updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pv_reserves_severity_chk CHECK(severity IN ('observation','minor','major','blocking')), CONSTRAINT pv_reserves_status_chk CHECK(status IN ('open','resolved','waived')), CONSTRAINT pv_reserves_version_positive_chk CHECK(version > 0));--> statement-breakpoint
CREATE INDEX IF NOT EXISTS pv_reserves_project_id_idx ON pv_reserves(project_id);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS pv_reserve_lots (reserve_id integer NOT NULL REFERENCES pv_reserves(id) ON DELETE CASCADE, lot_id integer NOT NULL REFERENCES lots(id), CONSTRAINT pv_reserve_lots_reserve_lot_unique UNIQUE(reserve_id,lot_id));--> statement-breakpoint
CREATE TABLE IF NOT EXISTS pv_reserve_events (id serial PRIMARY KEY, reserve_id integer NOT NULL REFERENCES pv_reserves(id) ON DELETE CASCADE, from_status text, to_status text, comment text, payload jsonb, actor text NOT NULL, created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS pv_package_revisions (id serial PRIMARY KEY, package_id integer NOT NULL REFERENCES pv_packages(id) ON DELETE CASCADE, revision_number integer NOT NULL, manifest jsonb NOT NULL, manifest_sha256 text NOT NULL, pdf_storage_key text NOT NULL, pdf_sha256 text NOT NULL, pdf_page_count integer NOT NULL, confirmed_by text NOT NULL, confirmed_at timestamp NOT NULL, CONSTRAINT pv_package_revisions_package_revision_unique UNIQUE(package_id,revision_number), CONSTRAINT pv_package_revisions_number_positive_chk CHECK(revision_number > 0), CONSTRAINT pv_package_revisions_manifest_sha256_chk CHECK(manifest_sha256 ~ '^[0-9a-f]{64}$'), CONSTRAINT pv_package_revisions_pdf_sha256_chk CHECK(pdf_sha256 ~ '^[0-9a-f]{64}$'), CONSTRAINT pv_package_revisions_page_count_chk CHECK(pdf_page_count > 0));--> statement-breakpoint
CREATE TABLE IF NOT EXISTS pv_revision_reserves (revision_id integer NOT NULL REFERENCES pv_package_revisions(id) ON DELETE CASCADE, reserve_id integer NOT NULL REFERENCES pv_reserves(id), reserve_snapshot jsonb NOT NULL, snapshot_sha256 text NOT NULL, CONSTRAINT pv_revision_reserves_revision_reserve_unique UNIQUE(revision_id,reserve_id), CONSTRAINT pv_revision_reserves_snapshot_sha256_chk CHECK(snapshot_sha256 ~ '^[0-9a-f]{64}$'));--> statement-breakpoint
CREATE TABLE IF NOT EXISTS pv_package_events (id serial PRIMARY KEY, package_id integer NOT NULL REFERENCES pv_packages(id) ON DELETE CASCADE, event_type text NOT NULL, payload jsonb, actor text NOT NULL, created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);--> statement-breakpoint

CREATE OR REPLACE FUNCTION guard_pv_workflow() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_TABLE_NAME='marche_lot_assignments' AND NOT EXISTS (SELECT 1 FROM marches m JOIN lots l ON l.id=NEW.lot_id WHERE m.id=NEW.marche_id AND m.project_id=l.project_id) THEN RAISE EXCEPTION 'assignment lot must belong to marche project' USING ERRCODE='23514'; END IF;
  IF TG_TABLE_NAME='pv_packages' AND NOT EXISTS (SELECT 1 FROM marches m WHERE m.id=NEW.marche_id AND m.project_id=NEW.project_id AND m.contractor_id=NEW.contractor_id) THEN RAISE EXCEPTION 'package project, marche and contractor must agree' USING ERRCODE='23514'; END IF;
  IF TG_TABLE_NAME='pv_package_lots' AND NOT EXISTS (SELECT 1 FROM pv_packages p JOIN marche_lot_assignments a ON a.id=NEW.assignment_id JOIN lots l ON l.id=NEW.lot_id WHERE p.id=NEW.package_id AND a.marche_id=p.marche_id AND a.lot_id=NEW.lot_id AND a.removed_at IS NULL AND l.project_id=p.project_id) THEN RAISE EXCEPTION 'package lot requires active matching assignment' USING ERRCODE='23514'; END IF;
  IF TG_TABLE_NAME='pv_reserves' AND NOT EXISTS (SELECT 1 FROM projects p WHERE p.id=NEW.project_id) THEN RAISE EXCEPTION 'reserve project missing' USING ERRCODE='23514'; END IF;
  IF TG_TABLE_NAME='pv_reserves' AND ((NEW.marche_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM marches m WHERE m.id=NEW.marche_id AND m.project_id=NEW.project_id AND (NEW.contractor_id IS NULL OR m.contractor_id=NEW.contractor_id))) OR (NEW.contractor_id IS NOT NULL AND NEW.marche_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM marches m WHERE m.id=NEW.marche_id AND m.contractor_id=NEW.contractor_id))) THEN RAISE EXCEPTION 'reserve marche/contractor must agree with project' USING ERRCODE='23514'; END IF;
  IF TG_TABLE_NAME='pv_reserve_lots' AND NOT EXISTS (SELECT 1 FROM pv_reserves r JOIN lots l ON l.id=NEW.lot_id WHERE r.id=NEW.reserve_id AND r.project_id=l.project_id) THEN RAISE EXCEPTION 'reserve lot must belong to reserve project' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION guard_pv_draft_document() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' THEN IF pg_trigger_depth()>1 OR NOT EXISTS(SELECT 1 FROM pv_packages WHERE id=OLD.package_id) THEN RETURN OLD; END IF; IF NOT EXISTS(SELECT 1 FROM pv_packages WHERE id=OLD.package_id AND status='draft') THEN RAISE EXCEPTION 'package documents may only change while draft' USING ERRCODE='23514'; END IF; RETURN OLD; END IF; IF NOT EXISTS(SELECT 1 FROM pv_packages WHERE id=NEW.package_id AND status='draft') THEN RAISE EXCEPTION 'package documents may only change while draft' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION guard_pv_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' AND pg_trigger_depth()>0 THEN RETURN OLD; END IF; RAISE EXCEPTION 'PV workflow ledger rows are immutable' USING ERRCODE='23514'; END $$;--> statement-breakpoint
DROP TRIGGER IF EXISTS marche_lot_assignment_project_trg ON marche_lot_assignments; CREATE TRIGGER marche_lot_assignment_project_trg BEFORE INSERT OR UPDATE ON marche_lot_assignments FOR EACH ROW EXECUTE FUNCTION guard_pv_workflow();--> statement-breakpoint
DROP TRIGGER IF EXISTS pv_package_consistency_trg ON pv_packages; CREATE TRIGGER pv_package_consistency_trg BEFORE INSERT OR UPDATE ON pv_packages FOR EACH ROW EXECUTE FUNCTION guard_pv_workflow();--> statement-breakpoint
DROP TRIGGER IF EXISTS pv_package_lot_consistency_trg ON pv_package_lots; CREATE TRIGGER pv_package_lot_consistency_trg BEFORE INSERT OR UPDATE ON pv_package_lots FOR EACH ROW EXECUTE FUNCTION guard_pv_workflow();--> statement-breakpoint
DROP TRIGGER IF EXISTS pv_reserve_consistency_trg ON pv_reserves; CREATE TRIGGER pv_reserve_consistency_trg BEFORE INSERT OR UPDATE ON pv_reserves FOR EACH ROW EXECUTE FUNCTION guard_pv_workflow();--> statement-breakpoint
DROP TRIGGER IF EXISTS pv_reserve_lot_project_trg ON pv_reserve_lots; CREATE TRIGGER pv_reserve_lot_project_trg BEFORE INSERT OR UPDATE ON pv_reserve_lots FOR EACH ROW EXECUTE FUNCTION guard_pv_workflow();--> statement-breakpoint
DROP TRIGGER IF EXISTS pv_package_document_draft_trg ON pv_package_documents; CREATE TRIGGER pv_package_document_draft_trg BEFORE INSERT OR UPDATE OR DELETE ON pv_package_documents FOR EACH ROW EXECUTE FUNCTION guard_pv_draft_document();--> statement-breakpoint
DROP TRIGGER IF EXISTS pv_reserve_events_append_only_trg ON pv_reserve_events; CREATE TRIGGER pv_reserve_events_append_only_trg BEFORE UPDATE OR DELETE ON pv_reserve_events FOR EACH ROW EXECUTE FUNCTION guard_pv_immutable();--> statement-breakpoint
DROP TRIGGER IF EXISTS pv_package_revisions_immutable_trg ON pv_package_revisions; CREATE TRIGGER pv_package_revisions_immutable_trg BEFORE UPDATE OR DELETE ON pv_package_revisions FOR EACH ROW EXECUTE FUNCTION guard_pv_immutable();--> statement-breakpoint
DROP TRIGGER IF EXISTS pv_revision_reserves_immutable_trg ON pv_revision_reserves; CREATE TRIGGER pv_revision_reserves_immutable_trg BEFORE UPDATE OR DELETE ON pv_revision_reserves FOR EACH ROW EXECUTE FUNCTION guard_pv_immutable();--> statement-breakpoint
DROP TRIGGER IF EXISTS pv_package_events_append_only_trg ON pv_package_events; CREATE TRIGGER pv_package_events_append_only_trg BEFORE UPDATE OR DELETE ON pv_package_events FOR EACH ROW EXECUTE FUNCTION guard_pv_immutable();