// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/devis-checks/EmailPreviewModal.tsx": () => import("../components/mockups/devis-checks/EmailPreviewModal.tsx"),
  "./components/mockups/devis-checks/InlinePopover.tsx": () => import("../components/mockups/devis-checks/InlinePopover.tsx"),
  "./components/mockups/devis-checks/OutboxFooter.tsx": () => import("../components/mockups/devis-checks/OutboxFooter.tsx"),
  "./components/mockups/devis-detail/Current.tsx": () => import("../components/mockups/devis-detail/Current.tsx"),
  "./components/mockups/devis-detail/InlineCollapse.tsx": () => import("../components/mockups/devis-detail/InlineCollapse.tsx"),
  "./components/mockups/devis-detail/PeekBars.tsx": () => import("../components/mockups/devis-detail/PeekBars.tsx"),
  "./components/mockups/devis-detail/TabbedAdvanced.tsx": () => import("../components/mockups/devis-detail/TabbedAdvanced.tsx"),
  "./components/mockups/devis-row/AnchoredTotals.tsx": () => import("../components/mockups/devis-row/AnchoredTotals.tsx"),
  "./components/mockups/devis-row/CompactToolbar.tsx": () => import("../components/mockups/devis-row/CompactToolbar.tsx"),
  "./components/mockups/devis-row/Current.tsx": () => import("../components/mockups/devis-row/Current.tsx"),
  "./components/mockups/devis-row/TwoTier.tsx": () => import("../components/mockups/devis-row/TwoTier.tsx")
};
