// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/devis-row/AnchoredTotals.tsx": () => import("../components/mockups/devis-row/AnchoredTotals.tsx"),
  "./components/mockups/devis-row/CompactToolbar.tsx": () => import("../components/mockups/devis-row/CompactToolbar.tsx"),
  "./components/mockups/devis-row/Current.tsx": () => import("../components/mockups/devis-row/Current.tsx"),
  "./components/mockups/devis-row/TwoTier.tsx": () => import("../components/mockups/devis-row/TwoTier.tsx")
};
