/**
 * Stable machine-readable error codes for the design-contract upload flow
 * Mirrored in client + server so the React form can map to a
 * specific UI message without parsing free-text.
 */
export const DESIGN_CONTRACT_ERROR_CODES = {
  INVALID_PDF: "DESIGN_CONTRACT_INVALID_PDF",
  PARSE_FAILED: "DESIGN_CONTRACT_PARSE_FAILED",
  AI_TRANSIENT: "DESIGN_CONTRACT_AI_TRANSIENT",
  NOT_A_DESIGN_CONTRACT: "DESIGN_CONTRACT_NOT_RECOGNISED",
  MILESTONES_DONT_SUM_TO_TOTAL: "DESIGN_CONTRACT_MILESTONES_TOTAL_MISMATCH",
  MILESTONES_PCT_NOT_100: "DESIGN_CONTRACT_MILESTONES_PCT_NOT_100",
  STAGING_KEY_NOT_FOUND: "DESIGN_CONTRACT_STAGING_KEY_NOT_FOUND",
  PROJECT_NOT_FOUND: "DESIGN_CONTRACT_PROJECT_NOT_FOUND",
} as const;

export type DesignContractErrorCode =
  (typeof DESIGN_CONTRACT_ERROR_CODES)[keyof typeof DESIGN_CONTRACT_ERROR_CODES];
